// dx12_tool_search 用の検索語(日本語/英語の言い換え・よくある言い方)。ツール名(dx12_ を除く)→ 語のリスト。
// 説明文は使い分けの解説が中心で、「ユーザーが実際に口にする言い方」は入っていないことが多い。ここで補う。
// エンジンのマニフェストに keywords があればそちらも合わせて使う(catalog.ts)。
// 追加の作法: 新しいツールを足したら、ここに 1 行足して eval/discovery_tasks.json に代表クエリを足す。

export const SEARCH_HINTS: Record<string, string> = {
  // shell 5 本
  tool_search: "ツール検索 探す どのツール 名前が分からない 検索 search find tool 目的のツール",
  tool_describe: "ツール詳細 仕様 引数 スキーマ 例 describe 使い方を調べる 引数の確認",
  call: "実行 任意のツール 呼ぶ dryRun call 撃つ 検証してから実行 旧ツール名で実行",
  doctor: "接続 繋がらない つながらない 診断 起動していない エンジンが落ちた ポート 疎通 原因 起動手順 自己診断 エンジンに繋がらない 接続できない 応答がない 版ずれ",
  guide: "使い方 ガイド 手順 やり方 ヘルプ 最短手順 チュートリアル 注意 ルール 危険操作 仮想入力の運用",
  // 接続・自己記述・ログ
  ping: "疎通 接続確認 生きてる 状態 モード sceneDirty 未保存 protocol version パス baseDir assetsDir 起動確認",
  get_mode: "モード Editor Playing 再生中か 現在のモード",
  get_log: "ログ エラーログ 警告 例外 出力 console 確認 見たい 履歴 dx12_engine.log",
  get_script_errors: "スクリプトエラー Lua エラー ロードエラー 壊れている 例外 確認",
  diagnose: "診断 エンジン診断 健全性 壊れていないか アセット欠落 テクスチャ 自己診断 チェック",
  describe_components: "コンポーネント一覧 仕様 フィールド 型 jsonKey どんな項目があるか スキーマ",
  describe_mcp_params: "引数 パラメータ一覧 method 受け付けるキー スキーマ",
  describe_lua_api: "Lua API 一覧 関数 リファレンス scene physics camera audio 使えるAPI",
  describe_anim_graph: "アニメグラフ ステート 遷移 パラメータ",
  describe_shader_contract: "シェーダー 契約 入出力 cbuffer 制約 hlsl の書き方",
  list_shader_templates: "シェーダーテンプレート 水 海 ひな形 サンプル",
  // エンティティ読み取り
  list_entities: "一覧 シーンの中身 何が置いてある 全部 エンティティ列挙 オブジェクト一覧 名前一覧 エンティティ数 ids entityId",
  get_entity: "詳細 位置 座標 コンポーネント 値 読む 確認 プレイヤー 現在の値 inspect transform 情報 データ",
  find_entity: "名前で探す 名前検索 完全一致 見つける entityId を得る",
  query_entities: "タグで探す 範囲 領域 矩形 box XZ 検索 tag",
  get_hierarchy: "階層 親子 ツリー 子 hierarchy 構造",
  get_bounds: "境界 バウンディングボックス サイズ 大きさ AABB 範囲 寸法",
  list_scenes: "シーン一覧 シーンファイル 開けるシーン",
  list_assets: "アセット一覧 ファイル一覧 モデル テクスチャ 音 画像 何があるか",
  // 編集
  set_transform: "位置 移動 回転 スケール 大きさ 座標 動かす 向き 変形 壁 床 オブジェクトを動かす position rotation scale",
  set_component: "コンポーネント 値 書き換える 変更 設定 ライト 強さ 明るさ 色 プロパティ 追加 pointLight intensity rigidBody collider カメラ 編集",
  remove_component: "コンポーネント削除 外す 取り除く",
  set_parent: "親子付け 親を設定 階層 子にする reparent 付ける",
  group_entities: "グループ化 まとめる 空の親 グループを作る",
  rename_entity: "名前変更 改名 リネーム",
  select_entity: "選択 選ぶ フォーカス ハイライト エディタで選択",
  focus_camera: "カメラを向ける フォーカス 注目 視点を合わせる",
  set_pbr: "PBR 金属 粗さ 質感 メタリック roughness metallic 材質 単体の値",
  set_color: "色 カラー 塗る 基本色 頂点色 着色 base color",
  set_texture: "テクスチャ 貼る 画像 albedo normal roughness 単体",
  material_apply: "マテリアル まとめて PBR テクスチャ 貼る 木材 金属 アルベド 法線 ラフネス 4点 質感 素材 texture set 一括",
  set_mesh_shader: "メッシュシェーダー カスタムシェーダー 割り当て 適用",
  set_mesh_shader_params: "シェーダー パラメータ p1 p2 uniform 値",
  set_sprite_shader: "スプライト シェーダー 2D",
  set_scene_settings: "シーン設定 スカイボックス 環境マップ IBL デカールアトラス 物理大気 大気 空 時刻 夕焼け 朝焼け 昼夜 天気",
  get_scene_settings: "シーン設定 スカイボックス 環境マップ 読む",
  // 生成
  create_entity: "作成 作る 箱 床 壁 ボックス ライト 追加 生成 置く 名前を付ける 新規 新しい 配置 エンティティ",
  spawn_box: "箱 足場 床 壁 ボックス 置く 直方体 platform 大きな箱",
  spawn_sphere: "球 ボール スフィア 置く",
  spawn_coin: "コイン 円盤 拾う アイテム",
  spawn_model: "モデル 配置 読み込み glb gltf fbx 3D 置く スポーン キャラ 建物 メッシュを置く 座標に置く",
  spawn_prefab: "プレハブ インスタンス 生成 テンプレート",
  create_prefab: "プレハブを作る 保存 テンプレート化",
  duplicate_entity: "複製 コピー 増やす clone",
  delete_entity: "削除 消す 除去 取り除く 破棄",
  scatter: "散らす 散布 ばら撒く 大量に置く 100本 たくさん 森 草 岩 群れ ランダム配置 木を植える",
  scene_scaffold: "骨格 グループ 命名 スキャフォールド 最初に作る 整理された足場 LVL ENV",
  scene_write: "シーンを丸ごと 一括生成 まとめて配置 部屋 一式 ステージ JSON 大量配置 一気に作る",
  apply_scene_spec: "ステージを作って FPS ステージ アリーナ レベル 部屋 街 庭 散歩できる庭 廊下 ホラーの廊下 ショーケース 一式 まとめて生成 一括生成 仕様 仕様 JSON 宣言的 相対配置 円形に並べる 円形に 格子状 等間隔 壁に沿って 上に載せる 右に置く 散らす 差分 差分だけ 計画だけ 何を作って何を更新する 冪等 2 回撃っても 検証つき 到達できるか 台の上 ライト 3 灯 カメラで狙う 木 花 池 ベンチ 柱 椅子 ランプ テーブル 街並み 建物 specPatch 撃ち直し 迷路 ダンジョン 草原 倉庫 教室 本棚 机 マップを作る 歩ける 散らした",
  scene_spec_export: "現在のシーンを仕様に 仕様 JSON に書き出す エクスポート 手で作ったシーンを宣言的に 仕様に起こす 往復 シーンから仕様",
  organize_scene: "整理 命名規則 グループ分け 散らかった 改名 一括整理",
  validate_naming: "命名チェック 名前の規則 検査 デフォルト名",
  validate_layout: "配置検査 埋まっている 浮いている めり込み 重なり Z-fighting コライダー 検査 レイアウト チェック",
  validate_scene: "シーン検査 アセット欠落 参照切れ 検証 バリデーション",
  // シーン/プロジェクト
  open_scene: "シーンを開く 読み込む ロード 切り替え 開き直す",
  open_project: "プロジェクトを開く 切り替え",
  new_scene: "新規シーン 空のシーン 作り直す",
  save_scene: "保存 セーブ シーンを保存 書き出す",
  build_game: "ビルド 配布 パッケージ 書き出し exe 出力 リリース",
  // Undo
  undo: "元に戻す 取り消す 取消 アンドゥ 直前の変更 戻す さっきの変更 ctrl+z",
  redo: "やり直す リドゥ 取り消しを戻す",
  transaction_begin: "トランザクション開始 まとめて 1つの取り消し 一括 begin",
  transaction_commit: "トランザクション確定 コミット 確定",
  transaction_rollback: "トランザクション巻き戻し ロールバック 丸ごと戻す 失敗したら戻す",
  transaction_status: "トランザクション状態 開いているか",
  batch: "バッチ まとめて実行 複数の操作 一括 往復を減らす 連続実行",
  // 再生・入力
  play: "再生 プレイ 実行 ゲームを動かす 開始 Play テストプレイ 起動して遊ぶ ゲーム再生",
  stop: "停止 止める ストップ 再生終了 エディタに戻る",
  get_play_session: "プレイセッション 人のプレイ 記録 入力履歴 操作記録",
  key_down: "キーを押し続ける 押下 キーボード入力 ゲームへの入力 WASD",
  key_up: "キーを離す 解放",
  key_press: "キーを押す 一瞬 タップ キー入力",
  mouse_move: "マウス移動 視点を回す カメラ回転 一人称 向きを変える look",
  step_frames: "フレームを進める 決定論 固定時間 ステップ 時間を進める 一時停止して進める deterministic",
  play_script: "台本 スクリプト入力 自動プレイ 断言 assert ゴールまで行けるか 入力の台本 テストプレイ 検証 シナリオ",
  measure_player: "プレイヤー実測 移動速度 ジャンプ高さ 歩行 能力測定",
  check_reachable: "到達性 行けるか ゴールへ届く 詰み クリア可能 経路 ナビメッシュ 検査",
  autoplay: "自動プレイ 走破 クリアできるか 自動で歩かせる 実走",
  record_playtest: "プレイを記録 回帰テスト作成 録画 保存 人のプレイ",
  run_playtests: "プレイテスト全部 回帰テスト 実行 保存済み まとめて実行 リグレッション",
  ui_click: "ゲーム内UIを押す ボタンを押す メニュー操作 HUD クリック",
  // 仮想入力(エディタ UI)
  imgui_virtual_input: "仮想入力 エディタUI操作 モード ON OFF 人のカーソルを奪わない --background",
  imgui_pointer: "クリック ポインタ ボタンを押す ドラッグ エディタUI 値欄 Inspector 入力 マウス 仮想",
  imgui_key: "キー入力 エディタUI ショートカット 文字入力 仮想キー テキスト入力",
  imgui_find: "UI要素を探す ウィンドウ ボタン 位置 座標 メニュー 見つける パネル 開く エディタ画面",
  imgui_screenshot: "エディタのスクリーンショット ImGui込み UI撮影 パネル画像",
  // 物理・観測
  raycast: "レイキャスト 光線 当たり 衝突判定 コライダー 視線",
  raycast_precise: "精密レイ 三角形 描画メッシュ 正確なヒット",
  overlap_box: "箱で重なり判定 範囲内のエンティティ",
  overlap_sphere: "球で重なり判定 半径内",
  get_physics_state: "物理状態 速度 velocity 接地 重力",
  audio_state: "音 サウンド オーディオ 再生中の音 ボイス",
  brain_state: "AI 状態 ブレイン 敵 追跡 行動",
  // 描画設定
  get_post_process: "ポストプロセス 読む 現在値 ブルーム トーンマップ 露出",
  set_post_process: "ポストプロセス ブルーム トーンマップ 露出 bloom exposure tonemap 色調補正 グレーディング DOF 被写界深度 ビネット 画面効果 コントラスト 彩度",
  get_ssao: "SSAO 環境遮蔽 読む 現在値 AO",
  set_ssao: "SSAO 環境遮蔽 AO 暗がり 隅の影 ambient occlusion",
  get_occlusion: "オクルージョンカリング Hi-Z 読む",
  set_occlusion: "オクルージョンカリング Hi-Z 見えない物を描かない 最適化",
  vg_stats: "仮想ジオメトリ Nanite クラスタ カリング 統計 vgeo 何万ポリゴン 巨大メッシュ LOD 可視クラスタ",
  set_virtual_geometry: "仮想ジオメトリ Nanite GPU カリング ON OFF vgeo lodPixelError 巨大メッシュ 数千万ポリゴン",
  get_render_scale: "レンダースケール 解像度 読む",
  set_render_scale: "レンダースケール 解像度 内部解像度 軽くする 負荷",
  get_depth_prepass: "深度プリパス 読む",
  set_depth_prepass: "深度プリパス オーバードロー 最適化",
  get_ssr: "SSR 反射 読む",
  set_ssr: "SSR 反射 映り込み 床の反射 screen space reflection",
  get_ssgi: "SSGI 間接光 読む",
  get_gi_mode: "GI モード 読む legacy new 空の遮蔽 グローバルイルミネーション",
  set_gi_mode: "GI モード 切り替え 新しいGI legacy new 空の遮蔽 DDGI 環境光 室内",
  migrate_gi: "GI 移行 新しいGIに切り替える 旧に戻す 自動フィット DDGI 格子 環境光 ambient 0 SSGI RT影 新規シーン既定",
  set_ssgi: "SSGI 間接光 グローバルイルミネーション GI 色の回り込み",
  get_contact_shadow: "コンタクトシャドウ 読む",
  set_contact_shadow: "コンタクトシャドウ 接地影 細かい影",
  get_normal_filter: "法線フィルタ 読む",
  set_normal_filter: "法線フィルタ スペキュラエイリアス ちらつき 法線 ラフネス",
  get_shadow_pcss: "PCSS 影 読む",
  set_shadow_pcss: "PCSS ソフトシャドウ 影のぼかし 柔らかい影 shadow",
  get_dxr: "DXR レイトレ 読む 対応",
  set_dxr: "DXR レイトレーシング 反射 影 GI ハードウェアRT",
  get_taa: "TAA アンチエイリアス 読む",
  set_taa: "TAA アンチエイリアス ジャギー ちらつき 揺れ",
  get_volumetric_fog: "ボリュームフォグ 霧 読む",
  set_volumetric_fog: "霧 フォグ ボリュームフォグ 空気感 ゴッドレイ もや 光の筋",
  render_debug: "デバッグ表示 中間バッファ 可視化 法線 深度 G-buffer AO 見え方の切り分け なぜ変に見えるか",
  // ライティング
  list_lights: "ライト一覧 灯数 光源 バジェット ライトの数",
  set_sun: "太陽 サン ディレクショナル 日光 方位 高度 色温度 明るさ 影 時間帯",
  apply_lighting_preset: "ライティングプリセット 昼 夕方 夜 屋内 ホラー スタジオ 雰囲気 一括 明るさ",
  look_library: "ルック 一覧 絵作り 雰囲気の種類 プリセット一覧",
  look_apply: "ルック 絵作り 雰囲気 夕暮れ 夜 ホラー調 一括 色調 太陽 霧 空 ポスト まとめて 映画的 ムード",
  scene_env: "環境 スカイ HDR 環境マップ 空を設定",
  // エフェクト
  vfx_library: "エフェクト一覧 パーティクルの種類 レシピ 炎 煙 何が作れるか",
  vfx_apply: "エフェクト 炎 松明 焚き火 煙 火花 爆発 魔法 パーティクル 配置 たいまつ 置く 光 雨 雪 蛍",
  vfx_preview: "エフェクト確認 連写 出ているか プレビュー",
  list_particle_layers: "パーティクルレイヤー 一覧",
  add_particle_layer: "パーティクルレイヤー 追加 発生器 層",
  remove_particle_layer: "パーティクルレイヤー 削除",
  decal_library: "デカール 一覧 汚れ 傷 種類",
  decal_apply: "デカール 汚れ 傷 弾痕 焦げ 血 苔 水たまり 投影 経年 ダメージ",
  sequence_author: "演出 カットシーン シーケンス 台本から Lua カメラワーク フェード ムービー イベント 演出を作る",
  sequence_preview: "演出プレビュー シーケンス確認",
  // dx12_sequence(.dxseq。エンジンの sequence_* を op で束ねた Core ツール)。旧方式(台本 → Lua)の sequence_author とは別。
  sequence: "シーケンス シーケンサー タイムライン カットシーン キーフレーム カメラワーク 時間軸 演出 dxseq トラック カット マーカー 編集 評価 スクラブ 再生 自動再生 ムービー シネマティック カメラを動かす",
  polish_audit: "仕上がり 安っぽい 品質の測定 スコア 改善点 見栄え 監査",
  // 地形
  terrain_create: "地形を作る 地形 新規 ハイトフィールド 空の地形",
  terrain_generate: "地形生成 山 丘 峡谷 ハイトフィールド プロシージャル 自動生成 山を作る 地面 ノイズ",
  terrain_sculpt: "地形を彫る 高さ 盛る 削る 均す 隆起",
  terrain_erode: "浸食 侵食 風化 リアルな地形 水",
  terrain_paint: "地形ペイント 塗る テクスチャレイヤー",
  terrain_autopaint: "自動ペイント 高さと傾斜で塗り分け 雪 岩 草 割り当て",
  terrain_set_layers: "地形レイヤー 雪 岩 草 土 テクスチャ割り当て スプラット 4層",
  terrain_splat_info: "スプラット情報 塗り 確認",
  terrain_sample: "地形の高さを取る 標高 サンプル",
  sculpt_create: "スカルプト 作成 洞窟 アーチ 異形 頂点編集",
  sculpt_make_editable: "スカルプト 編集可能にする メッシュ変換",
  sculpt_brush: "スカルプト ブラシ 彫る 頂点",
  // ナビ
  navmesh_build: "ナビメッシュ 生成 焼く ベイク 経路探索 歩ける場所 AI移動",
  navmesh_settings: "ナビメッシュ 設定 パラメータ エージェント半径",
  navmesh_info: "ナビメッシュ 情報 ポリゴン数",
  navmesh_path: "経路 パス 探索 最短経路 A地点からB地点",
  navmesh_sample: "ナビメッシュ上の点 最寄り",
  navmesh_raycast: "ナビメッシュ レイ 視線",
  navmesh_debug: "ナビメッシュ 可視化 表示",
  navmesh_clear: "ナビメッシュ 消す 削除",
  // Lua
  create_lua_component: "Lua スクリプト 作成 コンポーネント 挙動 書く 回転 ゲームロジック 新しいスクリプト 貼る 付ける アタッチ ファイルを書く",
  attach_lua_component: "Lua を付ける アタッチ 既存スクリプトを貼る",
  read_lua_component: "Lua を読む スクリプト内容",
  get_lua_component_state: "Lua プロパティ 状態 値",
  set_lua_property: "Lua プロパティ 値を設定 パラメータ調整",
  reload_scripts: "スクリプト再読込 ホットリロード 再ロード",
  eval_lua: "Lua 即時実行 デバッグ 任意コード ワンライナー 試す",
  create_shader: "シェーダー作成 HLSL カスタムシェーダー 書く 水 ワイヤー",
  read_shader: "シェーダーを読む HLSL 内容 コンパイル結果",
  // UI
  ui_tree: "UI ツリー 構造 ウィジェット 一覧 ゲーム内UI",
  ui_design_brief: "UI デザイン 方針 ブリーフ 参照 スタイル",
  ui_audit: "UI 監査 検査 品質 ずれ 余白 フォント サイズ AIっぽい",
  ui_compose: "UI 組む タイトル画面 メニュー HUD ボタン ゲーム内UI 画面を作る レイアウト ブループリント 宣言的",
  ui_compare: "UI 比較 参照 差分 見た目を寄せる",
  ui_screenshot: "UI スクリーンショット ゲーム内UIの撮影",
  install_font: "フォント 導入 日本語フォント Noto Google Fonts 書体",
  // キャプチャ
  screenshot: "スクリーンショット スクショ 撮影 キャプチャ シーンビュー ポスト前 画像 撮る",
  screenshot_final: "最終画 スクリーンショット ポスト込み 人が見る 見た目 最終的な絵 撮影 仕上がり画面 撮る",
  screenshot_game_view: "ゲームビュー スクリーンショット ゲーム画面 カメラ",
  screenshot_from: "視点を指定して撮る ある視点から 位置とターゲット カメラ位置 アングル 撮影 スクショ 指定カメラ",
  focus_and_screenshot: "エンティティを写す フォーカスして撮影 対象を撮る 近くから",
  view_texture: "テクスチャを見る 画像確認 プレビュー",
  preview_model: "モデルのプレビュー サムネイル 確認",
  pick: "ピック 画面座標 何が映っているか クリック選択 精密",
  project_world_to_screen: "ワールド座標を画面座標に 投影 スクリーン位置",
  camera_path: "カメラを動かして連写 コンタクトシート ポップ ちらつき 時間方向の確認 一周",
  look_compare: "参照画像と比較 露出 色温度 コントラスト 絵づくりの差 測光 寄せる",
  get_editor_camera: "エディタカメラ 位置 読む",
  set_editor_camera: "エディタカメラ 固定 視点 移動 位置を設定",
  look_at: "向ける 注視 look at 向きを合わせる",
  snap_to_ground: "接地 地面に置く 落とす 床に合わせる",
  perceive: "知覚 見える 視認性 気づけるか 読めるか プレイヤーの目 可視 ID",
  // 性能・品質
  perf_stats: "FPS 性能 フレームレート パフォーマンス ボトルネック 重い CPU GPU 計測 フレーム時間 描画時間 統計",
  benchmark: "ベンチマーク 計測 平均FPS 負荷試験 uncap",
  quality_gate: "品質ゲート 総合検査 合否 作業の区切り まとめて検査 チェック 判定 出荷前",
  brief: "Brief 作品の意図 コンセプト ジャンル ムード 意図を書く",
  jev_ask: "Jev 判断 質問 外部判断",
  jev_eval: "Jev 評価 ケース",
  jev_status: "Jev 状態 キャッシュ",
  // アセット/Blender
  import_asset: "アセット取り込み インポート コピー モデル 素材 追加",
  asset_info: "アセット情報 メタ サイズ メッシュ数 プローブ",
  reload_assets: "アセット再読込 ホットリロード テクスチャ更新",
  move_asset: "アセット移動 リネーム 参照更新",
  delete_asset: "アセット削除 ファイル削除",
  asset_gap: "足りないモデル 不足アセット 欠けている素材",
  model_brief: "モデル仕様 規約 書き出し規約 サイズ 向き",
  blender_ensure: "Blender 起動 接続 自動起動",
  blender_export: "Blender 書き出し 取り込み glb 実寸検証",
  blender_polish: "Blender 仕上げ ベベル 法線 スムーズ",
  blender_material: "Blender マテリアル 素材を貼る",
  material_search: "素材 検索 探す テクスチャ 質感 PBR 高品質 polyhaven ambientcg CC0 木 床 石 金属 錆 布 革 レンガ コンクリ 大理石",
  blender_material_apply: "素材 貼る マテリアル テクスチャ 質感 PBR 高品質 実寸 縮尺 AO ORM 繰り返し 汚れ 錆 擦れ 風化 箱投影 blender オブジェクト",
  material_bake: "焼く ベイク 焼き込み テクスチャ マテリアル 高品質 PBR antiTile 風化 汚し 法線 AO ORM cycles エンジン用 手続きマテリアル",
  blender_place: "Blender 配置 レイアウト 並べた通りに置く 持ってくる 差分更新 リンク複製 インスタンス 並べ直し group モデルを一括で置く",
  // Git / マルチ
  git_status: "Git 状態 変更 差分 未コミット",
  git_branches: "Git ブランチ 一覧",
  git_checkout: "Git チェックアウト ブランチ切り替え",
  git_merge: "Git マージ",
  git_merge_abort: "Git マージ中止",
  git_commit: "Git コミット 保存 履歴",
  git_push: "Git プッシュ 送信 公開",
  git_pull: "Git プル 取得",
  git_fetch: "Git フェッチ",
  net_status: "マルチプレイ 状態 ネットワーク サーバ クライアント",
  net_setup: "マルチプレイ 設定 ホスト 接続",
  net_launch_test_client: "テストクライアント 起動 2窓 マルチプレイ確認",
};

// 英語の言い回し(同じ意味の日本語は上の表)。Claude は英語で検索することも多いので、主要なツールに足してある。
export const SEARCH_HINTS_EN: Record<string, string> = {
  tool_search: "search find tool discover which tool lookup",
  tool_describe: "describe schema arguments parameters usage details example",
  call: "call invoke run execute any tool method dry run",
  doctor: "doctor diagnose connection connect cannot connect engine not running port unreachable troubleshoot why cannot connect health check",
  guide: "guide how to help tutorial workflow rules safety best practice",
  ping: "ping health alive connection status version mode dirty",
  get_log: "log logs errors warnings engine log console output check errors",
  get_script_errors: "script errors lua errors load error broken script",
  list_entities: "list entities scene contents everything in the scene all objects names ids enumerate",
  get_entity: "get entity read components inspect player values transform properties details show",
  find_entity: "find entity by name lookup",
  query_entities: "query entities by tag box region",
  get_hierarchy: "hierarchy tree parent child structure",
  set_transform: "move resize rotate scale reposition translate position wall object transform place at coordinates",
  set_component: "set component modify property value light intensity brighter dimmer color change field update add component",
  create_entity: "create entity add new object cube box floor wall light name it spawn primitive",
  spawn_box: "box cube floor wall platform block primitive",
  spawn_model: "spawn model load glb gltf fbx mesh place asset at position instantiate 3d model file",
  delete_entity: "delete remove destroy entity object",
  duplicate_entity: "duplicate copy clone entity",
  scatter: "scatter randomly place many trees rocks grass hundreds forest populate",
  scene_write: "generate whole scene room level bulk create many objects json all at once one go floor walls lights entire stage",
  apply_scene_spec: "build a level stage arena room town garden corridor showcase in one shot declarative scene spec apply plan diff only idempotent relative placement place on top of to the right of next to grid ring circle around center scatter along wall evenly spaced lamp table chair pedestal three lights camera walkable reachability check pillars trees bench fps level layout generate whole scene from json spec patch retry maze dungeon meadow field warehouse classroom bookshelf desks map seed scattered",
  scene_spec_export: "export current scene as declarative spec json dump scene to spec round trip turn hand made scene into a spec",
  scene_scaffold: "scaffold groups naming skeleton structure organize new scene layout room",
  material_apply: "material textures albedo normal roughness metallic maps apply pbr wood metal set of textures",
  set_pbr: "pbr roughness metallic value material single",
  look_apply: "look mood atmosphere spooky evening night dusk horror cinematic grade whole scene style overall feel",
  apply_lighting_preset: "lighting preset day dusk night horror studio indoor mood evening",
  set_post_process: "post process bloom tonemap tone mapping exposure grading vignette depth of field contrast saturation tweak",
  get_ssao: "ssao ambient occlusion current values read settings",
  set_ssao: "ssao ambient occlusion change",
  vfx_apply: "vfx effect fire torch flame smoke sparks explosion particles burning campfire magic add effect",
  terrain_generate: "terrain generate mountain hills canyon heightfield landscape procedural",
  terrain_set_layers: "terrain layers snow rock grass dirt textures splat",
  create_lua_component: "lua script create write component behavior spin rotate attach new script code",
  ui_compose: "ui compose build screen menu main menu title screen hud buttons interface layout",
  screenshot_final: "final screenshot capture image what the player sees rendered frame postprocessed take screenshot",
  screenshot_from: "screenshot from camera position viewpoint angle capture image specific",
  focus_and_screenshot: "focus entity screenshot close up",
  perf_stats: "fps performance profile bottleneck frame time cpu gpu stats slow how many fps",
  benchmark: "benchmark measure average fps stress",
  play: "play start run game begin playing enter play mode",
  stop: "stop end playing return to editor exit play mode",
  play_script: "play script input script drive player assert goal reach scenario automated test keys",
  run_playtests: "run playtests all saved regression tests replay",
  quality_gate: "quality gate overall check verdict pass fail milestone review audit everything",
  imgui_find: "find ui element window button menu editor imgui open window panel",
  imgui_pointer: "click pointer mouse drag field inspector editor ui virtual click press button input value",
  imgui_key: "key input editor ui virtual keyboard type text shortcut",
  open_scene: "open scene load switch scene",
  save_scene: "save scene write scene to disk store",
  new_scene: "new scene empty scene create scene",
  navmesh_build: "navmesh bake build navigation mesh pathfinding walkable",
  check_reachable: "reachable reachability goal can reach path check unreachable stuck",
  undo: "undo revert last change last edit roll back previous action",
  redo: "redo reapply",
  transaction_rollback: "rollback transaction revert all",
  batch: "batch multiple operations at once bulk sequence",
  validate_layout: "validate layout buried floating overlap z fight collision check placement",
  diagnose: "diagnose engine health missing assets check",
  import_asset: "import asset copy model texture into project",
  eval_lua: "eval lua run code snippet debug immediate",
  get_editor_camera: "editor camera read position",
  set_editor_camera: "editor camera set fix viewpoint move camera",
  set_sun: "sun directional light angle time of day intensity color temperature",
  set_volumetric_fog: "fog volumetric mist haze god rays atmosphere",
  render_debug: "debug view buffer visualization normals depth gbuffer why looks wrong",
  decal_apply: "decal dirt grime stain scratch bullet hole blood moss puddle",
  sequence_author: "sequence cutscene camera fade timeline scripted event author",
  sequence: "sequence sequencer timeline cutscene keyframe keyframes camera work camera move track cut marker dxseq edit eval scrub play autoplay cinematic animate over time",
  polish_audit: "polish audit looks cheap quality score improve visuals",
  step_frames: "step frames advance deterministic time fixed timestep",
  key_press: "press key tap input game keyboard",
  mouse_move: "mouse move look turn camera first person rotate view",
  // 物理ハードウェア（Arduino / ESP32。hw_*）
  hw_list_ports: "ハードウェア arduino esp32 COM ポート 一覧 シリアル serial usb VID PID ch340 つないだ 挿した 実機 list ports",
  hw_status: "ハードウェア arduino esp32 状態 センサー 接続 つながってる チャンネル rtt 実機 status hardware sensor connected",
  hw_connect: "ハードウェア arduino esp32 接続 つなぐ 再接続 シリアル connect hardware serial",
  hw_disconnect: "ハードウェア arduino esp32 切断 ポート解放 disconnect hardware serial",
  hw_read: "ハードウェア arduino esp32 センサー 読む 集計 平均 ノイズ ジッタ ダイヤル read sample sensor jitter noise",
  hw_monitor: "ハードウェア arduino esp32 シリアルモニタ 生ログ 送受信 プロトコル デバッグ monitor serial log raw",
  hw_write: "ハードウェア arduino esp32 出力 書く LED 光らせる 振動 ブザー PWM write output led",
  hw_write_dangerous: "ハードウェア arduino esp32 ペルチェ ヒーター モーター dangerous 危険 出力 write peltier heater motor",
  hw_simulate: "ハードウェア arduino esp32 シミュレート 仮想デバイス 実機なし 偽 センサー値 テスト simulate virtual mock fake sensor",
  hw_calibrate: "ハードウェア arduino esp32 校正 キャリブレーション 範囲 min max ダイヤル センサー calibrate calibration range",
  hw_config_get: "ハードウェア arduino esp32 設定 hardware.json 読む config get actions pins match",
  hw_config_set: "ハードウェア arduino esp32 設定 hardware.json 書く 登録 デバイス config set register device actions pins",
  hw_flash: "ハードウェア arduino esp32 書き込み ファーム スケッチ アップロード コンパイル arduino-cli flash upload sketch firmware ino",
  hw_flash_status: "ハードウェア arduino esp32 書き込み 進捗 状態 ログ arduino-cli flash status progress",
};
